name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
         
    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd . --min-lines 3 --min-tokens 35 --threshold 0
      
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3
      
    - name: Testcases
      run: python BMS_Sender_test.py
